#!/usr/bin/env node

const testHelper = require('./src/test-helper');
const Database = require('./src/stores/database');
const bootstrapper = require('./src/bootstrapper');
const DocumentService = require('./src/services/document-service');

const section1 = `
# Lorem ipsum

## Nam interdum magna eu pretium laoreet

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo eros non augue vestibulum, vitae pellentesque nunc gravida. Nullam id elit quis arcu accumsan malesuada a non arcu. Aliquam bibendum turpis urna, nec tempor metus laoreet a. Cras consequat ex id tincidunt auctor. Aenean non elementum dolor. Morbi facilisis, ex et faucibus elementum, risus odio hendrerit justo, et ultricies libero risus a eros. Pellentesque eu auctor diam. Etiam quis odio sed mauris gravida porta sed sit amet nisi. Sed scelerisque tincidunt mattis. Donec vel orci faucibus, molestie nisi in, feugiat arcu. Nullam tincidunt sapien leo, convallis mollis neque accumsan at. Mauris vel placerat orci. Nam rutrum ullamcorper orci et scelerisque. Cras commodo ipsum purus, et venenatis leo lobortis quis.

Etiam facilisis, nisl sed posuere vehicula, enim libero accumsan dui, eget pulvinar diam nulla sed ligula. Fusce fringilla iaculis interdum. Mauris vitae posuere ante, non sollicitudin lectus. Quisque mollis ligula placerat semper tristique. Aliquam viverra feugiat diam, vel placerat tortor. Curabitur at lectus ac mauris varius pretium eget sagittis libero. Vivamus ultrices leo massa. Aenean vehicula ipsum eu gravida tempor. Proin pharetra, justo sit amet dictum hendrerit, elit ex pellentesque ipsum, ut accumsan elit nunc sit amet augue.

Aenean in sodales neque, nec imperdiet mi. Nam purus purus, accumsan quis dictum ac, interdum et est. Vivamus pulvinar est placerat tempus rhoncus. In sollicitudin, quam vestibulum vestibulum tempus, mauris lorem ultricies turpis, non gravida ex elit quis lectus. Integer ac tristique nisl. Suspendisse ac maximus urna. Etiam consequat eu dui eu scelerisque. Fusce blandit sagittis leo. Sed accumsan leo id odio auctor consectetur ut sed leo. Aenean aliquam tempor diam, eget mattis neque convallis non. Integer tincidunt mattis neque et condimentum.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ultricies erat, ac mollis nisi. Etiam vestibulum consectetur sodales. Suspendisse tempor lobortis enim, volutpat aliquet turpis iaculis id. Nam et fringilla erat, eu pulvinar tellus. Morbi pretium ante non iaculis feugiat. Integer feugiat tellus finibus lectus feugiat consectetur. Nulla luctus, est quis rhoncus porttitor, felis urna molestie elit, id placerat elit nunc sed nisl. Integer quis dui elit. Praesent dolor turpis, sagittis ut orci sed, aliquam tristique libero. Morbi mollis sagittis leo, et dictum quam dapibus vel. Vivamus ornare mauris sit amet ligula consequat, id imperdiet enim vestibulum.

Aenean condimentum massa eu lectus imperdiet luctus. Maecenas scelerisque condimentum arcu, quis faucibus nisi vulputate non. Praesent egestas diam a nisl ullamcorper pharetra. Quisque viverra porttitor dui quis feugiat. Donec non luctus massa. Mauris sit amet eros id lorem consequat elementum tempus et tellus. Fusce quam ipsum, aliquam feugiat mi vel, dapibus scelerisque nisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam feugiat convallis neque facilisis placerat. Fusce molestie nisl libero, id tempor felis gravida sit amet.
`;

const section2 = `
## Vivamus ac dictum mauris

Nam interdum magna eu pretium laoreet. Nam congue, justo vel fringilla luctus, sapien elit aliquam nunc, a bibendum est odio nec turpis. Nam id porttitor ex. Morbi sit amet felis vitae ex accumsan auctor eget quis sapien. Praesent id metus vitae diam sagittis suscipit ut in ex. Ut non venenatis quam, a pharetra lacus. Praesent venenatis volutpat nisl. Vivamus est erat, vehicula sed vestibulum non, vehicula blandit lorem. Nullam vehicula quis tortor ut pulvinar. Integer laoreet quam in risus pharetra, eu iaculis tortor volutpat. Sed sagittis mauris a congue commodo.

Pellentesque ac eros leo. Morbi et congue mauris, quis imperdiet velit. Vivamus congue velit in elit eleifend, ut molestie felis pellentesque. Pellentesque gravida ultrices odio, nec bibendum augue. Nunc sit amet mi elementum, venenatis lorem in, rutrum nunc. Quisque eget pharetra orci. Donec vel lorem in odio tempus gravida et et nibh. Proin nisl nibh, maximus eget dolor sit amet, luctus placerat justo.

Cras et tellus non turpis lobortis molestie in sollicitudin massa. Quisque at urna posuere, convallis felis sit amet, suscipit erat. Pellentesque at accumsan est, et dapibus diam. Nam volutpat consequat tortor, ac porttitor arcu consectetur vitae. Donec tempus, enim quis sodales pretium, sapien lacus sollicitudin libero, non sollicitudin tortor nulla in urna. Etiam venenatis tincidunt fermentum. Pellentesque sit amet turpis tincidunt, finibus enim eget, sollicitudin neque.

Vivamus in feugiat tellus, quis imperdiet ipsum. Duis vel libero quis metus sollicitudin feugiat. Aenean ipsum dui, lacinia sit amet volutpat sed, lobortis et nunc. Nulla convallis, arcu quis condimentum eleifend, sem nulla congue mauris, in congue neque justo vitae erat. Mauris facilisis purus eget justo tempus bibendum. Vivamus sed lacinia risus. Phasellus sit amet laoreet erat. Nulla egestas massa nec felis commodo finibus. Nulla consequat massa id ultrices efficitur. Sed maximus interdum auctor. Fusce a commodo orci. Sed dictum, tortor ac porttitor pharetra, arcu justo convallis turpis, vel tristique lacus tellus quis ligula.

Donec in nisl sollicitudin, luctus elit eget, viverra dolor. Aliquam eget odio id mauris rutrum blandit. Quisque vitae nunc sed risus varius dignissim. Quisque porttitor nibh ac ex facilisis posuere. Vivamus varius tempus ligula, at scelerisque mauris posuere nec. Aliquam in lorem sed leo mattis lacinia. Nullam sollicitudin rhoncus congue. Nam tristique vulputate leo et venenatis. Suspendisse et auctor ex. Quisque mattis mi at enim fermentum viverra. Sed mattis, ligula in molestie venenatis, nibh eros rhoncus purus, ut pharetra purus nunc sed metus.
`;

const section3 = `
## Nam tortor erat

Nam tortor erat, lacinia at cursus sit amet, dignissim id nibh. Nulla id nunc quis ante fringilla consequat sollicitudin non nisl. Cras tempus finibus mauris eget sodales. Donec congue sed erat sed efficitur. Donec vel leo erat. Sed commodo luctus turpis vel rutrum. Phasellus a tincidunt sem, a ullamcorper nibh. Nunc pharetra congue lacus eget maximus. Nullam venenatis sit amet nibh at consectetur. Mauris hendrerit leo lobortis feugiat ullamcorper. Sed mattis lectus at metus aliquam placerat. Donec malesuada lacus in arcu sagittis finibus. Proin blandit mi non libero vulputate tristique. Praesent quis tortor tempus, feugiat enim ac, porttitor libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;

Nunc gravida eleifend ante sed sagittis. Sed id turpis nibh. Donec id dui non lorem laoreet lacinia eget sed tellus. Curabitur at dolor aliquam, rhoncus elit eget, auctor leo. Duis ut justo facilisis, ultrices erat convallis, semper erat. Sed ac risus facilisis, vestibulum nunc ac, fringilla magna. Aenean eget nulla ac purus laoreet dictum quis a tortor. Donec ultricies varius ligula, ac ultrices odio ornare eu. Praesent venenatis viverra augue ut bibendum. Fusce commodo lectus a finibus euismod. Ut tempus mauris et dui feugiat hendrerit ac quis turpis. Aenean fringilla velit quis aliquam imperdiet. Suspendisse pellentesque tristique gravida. Nulla facilisi. Nunc laoreet, ex eu ullamcorper ullamcorper, libero lorem suscipit tellus, a hendrerit nunc dui sit amet lacus. Nam quis ante nisl.

Nulla vel dolor sed nisl ultricies lobortis. Donec mattis sem vitae ante sollicitudin maximus. Cras fringilla erat et nisi hendrerit, ut egestas tellus maximus. Proin vitae mauris in arcu rutrum ullamcorper. Nulla fringilla dapibus sapien vitae iaculis. Aliquam egestas sem sit amet urna ultrices, quis viverra massa tincidunt. Proin convallis congue risus vitae blandit. Suspendisse nec tellus nisl. Donec finibus augue volutpat ipsum suscipit sagittis.

Sed convallis et nunc et sagittis. Aenean sit amet ultricies enim. Nunc dapibus augue eu malesuada posuere. Vestibulum aliquet pharetra porttitor. Integer iaculis turpis eget urna efficitur vehicula. Quisque eu fermentum lorem, et viverra tortor. Vestibulum non leo ut libero lobortis elementum. Suspendisse vel sem tellus. Integer non magna ut dolor blandit ullamcorper eu eget leo.

Etiam cursus sem at dignissim facilisis. Morbi rhoncus porttitor tellus vitae ornare. Vivamus auctor eget mi et dictum. Ut accumsan interdum erat, eu lacinia turpis condimentum ullamcorper. Cras tempus vehicula pellentesque. Vivamus eleifend consequat enim eu venenatis. Integer ac magna vulputate, venenatis mauris id, laoreet justo. Pellentesque vestibulum convallis porta. Maecenas sit amet nisi dui. Integer scelerisque ullamcorper justo, vel bibendum nulla tempor a. Aenean pellentesque varius neque, vel pellentesque augue rhoncus eget. Aenean vestibulum eleifend tellus, sit amet interdum magna volutpat hendrerit.
`;

(async function seed() {

  const container = await bootstrapper.createContainer();

  const db = container.get(Database);
  const documentService = container.get(DocumentService);

  await testHelper.dropAllCollections(db);

  const documentId = 'SyMXOa6aM';
  const title = 'Lorem Ipsum';
  const sections = [
    {
      _id: 'Sye$V$ppTz',
      order: 1,
      type: 'markdown',
      content: {
        de: section1
      }
    },
    {
      _id: 'HybdE$6pTf',
      order: 1,
      type: 'quick-tester',
      content: {
        de: {
          teaser: 'Möchten Sie Ihr Wissen testen?',
          name: 'Fragen zum übermäßigen Quintsextakkord',
          tests: [
            {
              question: 'Wie heißen die Töne des übermäßigen Quintsextakkords in c-Moll?',
              answer: '_as_-_c_-_es_-_fis_.  \nZum Nachlesen: [J. Brahms, Op. 104, Nr. 5, ›Im Hebst‹, Schluss »wie nach dem Grab«](#brahms-doppeldominante).'
            }, {
              question: 'Wohin löst sich der übermäßige Quintsextakkord _as_-_c_-_es_-_fis_ als Sixte ajoutée auf?',
              answer: 'Es-Dur.  \nZum Nachlesen: [J. Brahms, Op. 104, Nr. 5, ›Im Hebst‹, »still ist die Flur«](#brahms-plagal).'
            }, {
              question: 'Wohin löst sich der Dominantseptakkord _as_-_c_-_es_-_ges_ auf?',
              answer: 'Des-Dur.  \nZum Nachlesen: [J. Brahms, Op. 104, Nr. 5, ›Im Hebst‹, zweite Phrase »sinkt auch«](#brahms-d7).'
            }, {
              question: 'In welche Tonart gehört der übermäßige Quintsextakkord _b_-_d_-_f_-_gis_ (als Doppeldominante)?',
              answer: 'nach d-Moll.  \nZum Nachlesen: [J. Brahms, Op. 104, Nr. 5, ›Im Hebst‹, Sequenz »er ahnt«](#brahms-sequenz).'
            }, {
              question: 'In welche Tonart gehört der übermäßige Quintsextakkord _c_-_e_-_g_-_ais_ (als Doppeldominante)?',
              answer: 'nach e-Moll.  \nZum Nachlesen: [J. Brahms, Op. 104, Nr. 5, ›Im Hebst‹, Sequenz »er ahnt«](#brahms-sequenz).'
            }, {
              question: 'In welche Tonart gehört der übermäßige Quintsextakkord _d_-_fis_-_a_-_his_ (als Doppeldominante)?',
              answer: 'nach fis-Moll.  \nZum Nachlesen: [J. Brahms, Op. 104, Nr. 5, ›Im Hebst‹, Sequenz »er ahnt«](#brahms-sequenz).'
            }, {
              question: 'Wohin löst sich der übermäßige Quintsextakkord _f_-_a_-_c_-_dis_ als Sixte ajoutée auf?',
              answer: 'nach C-Dur.'
            }, {
              question: 'Wie heißt der übermäßige Quintsextakkord in g-Moll?',
              answer: '_es_-_g_-_b_-_cis_'
            }, {
              question: 'Wie heißt der übermäßige Quintsextakkord in B-Dur?',
              answer: '_ges_-_b_-_des_-_e_'
            }, {
              question: 'Wie heißt der übermäßige Quintsextakkord in a-Moll?',
              answer: '_f_-_a_-_c_-_dis_'
            }, {
              question: 'Wie heißt der übermäßige Quintsextakkord in Es-Dur?',
              answer: '_ces_-_es_-_ges_-_a_'
            }
          ]
        }
      }
    },
    {
      _id: 'rkGdNdTaaM',
      order: 1,
      type: 'markdown',
      content: {
        de: section2
      }
    },
    {
      _id: 'Skmu4u6TaM',
      order: 1,
      type: 'markdown',
      content: {
        de: section3
      }
    }
  ];
  const user = {
    name: 'init-user'
  };

  await documentService.createDocumentRevision({ documentId, title, sections, user });

  await db.dispose();

})();
