export const PAGE_NAME = {
  doc: 'doc',
  docs: 'docs',
  room: 'room',
  user: 'user',
  index: 'index',
  login: 'login',
  users: 'users',
  admin: 'admin',
  tests: 'tests',
  search: 'search',
  batches: 'batches',
  revision: 'revision',
  register: 'register',
  dashboard: 'dashboard',
  resetPassword: 'reset-password',
  browserNotSupported: 'browser-not-supported',
  completePasswordReset: 'complete-password-reset',
  connectExternalAccount: 'connect-external-account',
  roomMembershipConfirmation: 'room-membership-confirmation'
};
