export const PAGE_NAME = {
  room: 'room',
  error: 'error',
  index: 'index',
  login: 'login',
  admin: 'admin',
  tests: 'tests',
  search: 'search',
  batches: 'batches',
  document: 'document',
  revision: 'revision',
  register: 'register',
  dashboard: 'dashboard',
  comparison: 'comparison',
  maintenance: 'maintenance',
  userProfile: 'user-profile',
  documentInput: 'document-input',
  resetPassword: 'reset-password',
  mediaLibraryItem: 'media-library-item',
  browserNotSupported: 'browser-not-supported',
  connectExternalAccount: 'connect-external-account',
  roomMembershipConfirmation: 'room-membership-confirmation'
};
