#!/usr/bin/env node

/* eslint no-console: 0 */
/* eslint no-await-in-loop: 0 */

require('babel-register')({ extensions: ['.jsx'] });
require('babel-polyfill');

const DocumentService = require('../src/services/document-service');
const serverBootstrapper = require('../src/bootstrap/server-bootstrapper');

const documentKeys = process.argv.slice(2);

(async function pruneEnv() {

  const container = await serverBootstrapper.createContainer();

  const documentService = container.get(DocumentService);

  for (const documentKey of documentKeys) {
    console.log(`Deleting document ${documentKey}...`);
    await documentService.deleteDocument({ documentKey });
  }

  await serverBootstrapper.disposeContainer(container);

  console.log('Done!');

})();
