#!/usr/bin/env node

/* eslint no-console: 0 */
/* eslint no-await-in-loop: 0 */

require('@babel/register');
require('core-js');

const DocumentService = require('../src/services/document-service').default;
const serverBootstrapper = require('../src/bootstrap/server-bootstrapper').default;

(async function regenerateDocs() {

  const container = await serverBootstrapper.createContainer();

  const documentService = container.get(DocumentService);

  const documentKeys = documentService.getDocumentKeys();

  for await (const documentKey of documentKeys) {
    console.log(`Regenerating document ${documentKey}...`);
    await documentService.regenerateLatestDocument(documentKey);
  }

  await serverBootstrapper.disposeContainer(container);

  console.log('Done!');

})();
