#!/usr/bin/env node

const path = require('path');
const util = require('util');
const glob = require('glob');
const testHelper = require('../src/test-helper');
const Database = require('../src/stores/database');
const { readJson } = require('../src/utils/file-helper');
const DocumentService = require('../src/services/document-service');
const serverBootstrapper = require('../src/bootstrap/server-bootstrapper');

(async function seed() {

  const container = await serverBootstrapper.createContainer();

  const db = container.get(Database);
  const documentService = container.get(DocumentService);

  await testHelper.dropAllCollections(db);

  const files = await util.promisify(glob)(path.join(__dirname, '../test/test-docs/*.json'));

  const docPayloads = await Promise.all(files.map(file => readJson(file)));

  await Promise.all(docPayloads.map(payload => documentService.createDocumentRevision(payload)));

  await serverBootstrapper.disposeContainer(container);

})();
