#!/usr/bin/env node
/* eslint-disable no-console */

require('@babel/register');
require('core-js');

const Cdn = require('../src/repositories/cdn').default;
const testHelper = require('../src/test-helper').default;
const serverBootstrapper = require('../src/bootstrap/server-bootstrapper').default;

(async function seed() {
  const container = await serverBootstrapper.createContainer(null, true);

  console.log('Getting cdn');
  const cdn = container.get(Cdn);

  console.log('Removing cdn buckets');
  await testHelper.removeAllBuckets(cdn);

  console.log('Ensuring cdn buckets exist');
  await testHelper.ensurePublicBucketExists(cdn);

  console.log('Disposing container');
  await serverBootstrapper.disposeContainer(container);
})();
